server.port=${PORT:8080}
spring.application.name=Worksphere

spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.url=${db_url}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always